### ISSUE TITLE
Tmpfs Plugin does not Umount correctly.

### ISSUE THREAD

**Issue by jmcgrath207** [rpm-software-management/mock#183]
### Short description of the problem

Keep on Getting a `Device is Busy` When using  the Tmpfs Plugin

### Output of `rpm -q mock`
Mock Version 1.4.9 on Centos 7

### Any additional notes
From the output of `df -h` it looks like It creates 2  tmpfs mounts when running but after  the command executes  it only removes one.

### During Run

```
[vagrant@BuildUtil ~]$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-LogVol00   38G  2.4G   36G   7% /
devtmpfs                         1.4G     0  1.4G   0% /dev
tmpfs                            1.5G     0  1.5G   0% /dev/shm
tmpfs                            1.5G  8.4M  1.4G   1% /run
tmpfs                            1.5G     0  1.5G   0% /sys/fs/cgroup
/dev/sda2                       1014M   63M  952M   7% /boot
tmpfs                            287M     0  287M   0% /run/user/1000
mock_chroot_tmpfs                2.0G  973M  1.1G  48% /var/lib/mock/epel-6-x86_64/root
tmpfs                            1.5G     0  1.5G   0% /var/lib/mock/epel-6-x86_64/root/dev/shm
```

### After Run

```
[vagrant@BuildUtil ~]$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-LogVol00   38G  2.4G   36G   7% /
devtmpfs                         1.4G     0  1.4G   0% /dev
tmpfs                            1.5G     0  1.5G   0% /dev/shm
tmpfs                            1.5G  8.4M  1.4G   1% /run
tmpfs                            1.5G     0  1.5G   0% /sys/fs/cgroup
/dev/sda2                       1014M   63M  952M   7% /boot
tmpfs                            287M     0  287M   0% /run/user/1000
mock_chroot_tmpfs                2.0G     0  2.0G   0% /var/lib/mock/epel-6-x86_64/root
```

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

```
[vagrant@BuildUtil ~]$ sudo mock --debug-config -r Util_mock_config_epel-6-x86_64.cfg --buildsrpm --spec Util.spec --sources . --resultdir=.
INFO: mock.py version 1.4.9 starting (python version = 2.7.5)...
Start: init plugins
INFO: tmpfs initialized
INFO: selinux disabled
Finish: init plugins
Start: run
INFO: Start(Util.spec)  Config(epel-6-x86_64)
Start: clean chroot
INFO: unmounting tmpfs.
Finish: clean chroot
Start: chroot init
INFO: mounting tmpfs at /var/lib/mock/epel-6-x86_64/root.
INFO: calling preinit hooks
INFO: enabled root cache
INFO: skipping root_cache aging check
Start: unpacking root cache
Finish: unpacking root cache
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
INFO: enabled ccache
INFO: enabled HW Info plugin
Mock Version: 1.4.9
INFO: Mock Version: 1.4.9
Start: yum install
Failed to set locale, defaulting to C
base                                                                                                                                                                                | 3.7 kB  00:00:00     
epel                                                                                                                                                                                | 4.7 kB  00:00:00     
sclo                                                                                                                                                                                | 2.9 kB  00:00:00     
sclo-rh                                                                                                                                                                             | 3.0 kB  00:00:00     
http://mirror.linux.duke.edu/pub/centos/6.9/updates/x86_64/repodata/repomd.xml: [Errno 14] curl#56 - "Recv failure: Connection reset by peer"
Trying other mirror.
updates                                                                                                                                                                             | 3.4 kB  00:00:00     
Package pigz-2.3.4-1.el6.x86_64 already installed and latest version
Package lbzip2-2.5-2.el6.x86_64 already installed and latest version
Nothing to do
Finish: yum install
Start: yum update
Failed to set locale, defaulting to C
No packages marked for update
Finish: yum update
Finish: chroot init
INFO: Enabled pm_request plugin
Start: buildsrpm
Start: rpmbuild -bs
warning: Could not canonicalize hostname: BuildUtil
Building target platforms: x86_64
Building for target x86_64
Wrote: /builddir/build/SRPMS/Util-1-0.19.el6.src.rpm
Finish: rpmbuild -bs
Finish: buildsrpm
INFO: Done(Util.spec) Config(Util_mock_config_epel-6-x86_64) 0 minutes 28 seconds
INFO: Results and/or logs in: .
INFO: Cleaning up build root ('cleanup_on_success=True')
Start: clean chroot
INFO: unmounting tmpfs.
WARNING: tmpfs-plugin: exception while umounting tmpfs! (cwd: /home/vagrant)
WARNING: tmpfs-plugin: exception while force umounting tmpfs! (cwd: /home/vagrant)
ERROR: Exception(Util.spec) Config(epel-6-x86_64) 0 minutes 33 seconds
INFO: Results and/or logs in: .
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 959, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 759, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 846, in run_command
    do_buildsrpm(config_opts, commands, buildroot, options, args)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 554, in do_buildsrpm
    cmd=cmd, post=None, clean=clean)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 501, in rebuild_generic
    commands.clean()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/backend.py", line 84, in clean
    self.buildroot.delete()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/buildroot.py", line 613, in delete
    util.rmtree(self.basedir, selinux=self.selinux)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 153, in rmtree
    rmtree(fullname, selinux=selinux, exclude=exclude)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 162, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: '/var/lib/mock/epel-6-x86_64/root'
[vagrant@BuildUtil ~]$ 
```

**Comment by praiskup** [comment]
Can you please retry with mock v1.4.19?  I believe this is fixed.

**Comment by jmcgrath207** [comment]
sorry I am not able to test this. I don't have access to the software anymore.

**Comment by praiskup** [comment]
OK, thanks.  I'm using tmpfs plugin on my box all the time, and I don't observe any issues.  So I suppose the problem was fixed.  To anybody: Please reopen if you are able to reproduce this issue.

**Comment by jnpkrn** [comment]
The problem is still present with `mock-1.4.21-1.fc32.noarch`.

Basically, I've run

```
mock -r fedora-rawhide-i386 --rebuild publican-4.3.2-14.fc32.src.rpm
```
(note: the particular mock hierarchy never existed before)

`^C`d the package _downloading_ phase, since I've realized I missed `-Nn`
and upon subsequent rerun, I've got

```
INFO: mock.py version 1.4.21 starting (python version = 3.8.0)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
INFO: Start(publican-4.3.2-14.fc32.src.rpm)  Config(fedora-rawhide-i386)
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.21
INFO: Mock Version: 1.4.21
ERROR: Exception(publican-4.3.2-14.fc32.src.rpm) Config(fedora-rawhide-i386) 0 minutes 0 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-rawhide-i386/result
ERROR: Command failed: 
 # /bin/mount -n --bind /tmp/mock-selinux-plugin.vagypnp1 /var/lib/mock/fedora-rawhide-i386/root/proc/filesystems
```

Indeed

```
$ mount -l | grep mock
tmpfs on /home/var/lib/mock/fedora-rawhide-i386/root/proc/filesystems type tmpfs (rw,nosuid,nodev,seclabel)
```

Another try:

```
$ mock -Nn -r fedora-rawhide-i386 --clean
INFO: mock.py version 1.4.21 starting (python version = 3.8.0)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 980, in <module>
    exitStatus = main()
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 757, in main
    result = run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 790, in run_command
    commands.clean()
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/backend.py", line 93, in clean
    self.buildroot.delete()
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/buildroot.py", line 706, in delete
    util.rmtree(self.basedir, selinux=self.selinux)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 257, in rmtree
    rmtree(fullname, selinux=selinux, exclude=exclude)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 257, in rmtree
    rmtree(fullname, selinux=selinux, exclude=exclude)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 265, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/var/lib/mock/fedora-rawhide-i386/root/proc/filesystems'
```

Considering, e.g., https://bugzilla.redhat.com/show_bug.cgi?id=1610456
it looks to me that RPM ecosystem related Python tooling doesn't receive
much signal-based (such as with Ctrl+C combo so natural for humans
wanting to fix their mistakes the moment they realize them!)
stress-testing, which makes these less robust than what the environment
of use demands at times, putting users at risk.

Take a beginner packager, for example, she might ditch any further
attempts after getting to this "deadlock".

**Comment by jnpkrn** [comment]
Or maybe the signal mishandling is suspected to be at fault here
exclusively, so I'd rather create a new issue?

**Comment by praiskup** [comment]
We got the same report again against mock v2.0;  the important part is:
```
INFO: unmounting tmpfs.
WARNING: tmpfs-plugin: exception while umounting tmpfs! (cwd: /home/vagrant)
WARNING: tmpfs-plugin: exception while force umounting tmpfs! (cwd: /home/vagrant)
```
For some reason mock isn't able to umount the tmpfs mount point (something is still
used there?) - and then following `rmtree` tracebacks.

**Comment by praiskup** [comment]
> We got the same report again against mock v2.0

I mean mock 2.0 in copr;  [build-log](https://download.copr.fedorainfracloud.org/results/kloxong/Testing/epel-8-x86_64/01304496-simscan-toaster/builder-live.log.gz)

**Comment by dkstiler** [comment]
Thanks paiskup for his help.
 i would like to add that this persists to fail without having enabled the mock's use_bootstrap_container experimental feature, when this settings is enabled on copr  with mock 2.0 then it manage to build successfully

**Comment by praiskup** [comment]
> i would like to add that this persists to fail without having enabled the mock's use_bootstrap_container

Yes, because when bootstrap is on, even package installation is run in container
(bootstrap one).  The processes are terminated with the container.
